name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  mod:
    runs-on: ubuntu-latest
    name: Check modules
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - uses: actions/checkout@v4
      - run: go mod tidy && git diff --exit-code go.mod go.sum
  build:
    name: Build the binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Build
        run: go build -v ./...
  test:
    runs-on: ubuntu-latest
    name: Run tests with ginkgo
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - uses: actions/checkout@v4
      - run: go vet ./...
      - run: go run github.com/onsi/ginkgo/v2/ginkgo run -r --randomize-all --randomize-suites --race --trace --keep-going
