name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mod:
    runs-on: ubuntu-latest
    name: Check modules
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26
      - uses: actions/checkout@v5
      - run: go mod tidy && git diff --exit-code go.mod go.sum
  build:
    name: Build the library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26
      - name: Build
        run: go build -v ./...
  test:
    runs-on: ubuntu-latest
    name: Run tests with ginkgo
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26
      - uses: actions/checkout@v5
      - run: go vet ./...
      - run: go run github.com/onsi/ginkgo/v2/ginkgo run -r --randomize-all --randomize-suites --race --trace --keep-going
